# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user16/Documents/mpags-cpp/mpags-cipher.git

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user16/Documents/mpags-cpp/mpags-cipher.git

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cpack --config ./CPackSourceConfig.cmake /home/user16/Documents/mpags-cpp/mpags-cipher.git/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/disk/homedisk/home/user16/Software/cmake-3.3.2-Linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user16/Documents/mpags-cpp/mpags-cipher.git/CMakeFiles /home/user16/Documents/mpags-cpp/mpags-cipher.git/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user16/Documents/mpags-cpp/mpags-cipher.git/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mpags-cipher

# Build rule for target.
mpags-cipher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mpags-cipher
.PHONY : mpags-cipher

# fast build rule for target.
mpags-cipher/fast:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/build
.PHONY : mpags-cipher/fast

#=============================================================================
# Target rules for targets named MPAGSCipher

# Build rule for target.
MPAGSCipher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MPAGSCipher
.PHONY : MPAGSCipher

# fast build rule for target.
MPAGSCipher/fast:
	$(MAKE) -f MPAGSCipher/CMakeFiles/MPAGSCipher.dir/build.make MPAGSCipher/CMakeFiles/MPAGSCipher.dir/build
.PHONY : MPAGSCipher/fast

#=============================================================================
# Target rules for targets named testCatch

# Build rule for target.
testCatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testCatch
.PHONY : testCatch

# fast build rule for target.
testCatch/fast:
	$(MAKE) -f Testing/CMakeFiles/testCatch.dir/build.make Testing/CMakeFiles/testCatch.dir/build
.PHONY : testCatch/fast

#=============================================================================
# Target rules for targets named testHello

# Build rule for target.
testHello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testHello
.PHONY : testHello

# fast build rule for target.
testHello/fast:
	$(MAKE) -f Testing/CMakeFiles/testHello.dir/build.make Testing/CMakeFiles/testHello.dir/build
.PHONY : testHello/fast

#=============================================================================
# Target rules for targets named testTransformChar

# Build rule for target.
testTransformChar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testTransformChar
.PHONY : testTransformChar

# fast build rule for target.
testTransformChar/fast:
	$(MAKE) -f Testing/CMakeFiles/testTransformChar.dir/build.make Testing/CMakeFiles/testTransformChar.dir/build
.PHONY : testTransformChar/fast

MPAGSCipher/CaesarCipher.o: MPAGSCipher/CaesarCipher.cpp.o

.PHONY : MPAGSCipher/CaesarCipher.o

# target to build an object file
MPAGSCipher/CaesarCipher.cpp.o:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/CaesarCipher.cpp.o
.PHONY : MPAGSCipher/CaesarCipher.cpp.o

MPAGSCipher/CaesarCipher.i: MPAGSCipher/CaesarCipher.cpp.i

.PHONY : MPAGSCipher/CaesarCipher.i

# target to preprocess a source file
MPAGSCipher/CaesarCipher.cpp.i:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/CaesarCipher.cpp.i
.PHONY : MPAGSCipher/CaesarCipher.cpp.i

MPAGSCipher/CaesarCipher.s: MPAGSCipher/CaesarCipher.cpp.s

.PHONY : MPAGSCipher/CaesarCipher.s

# target to generate assembly for a file
MPAGSCipher/CaesarCipher.cpp.s:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/CaesarCipher.cpp.s
.PHONY : MPAGSCipher/CaesarCipher.cpp.s

MPAGSCipher/CommandLineHelpers.o: MPAGSCipher/CommandLineHelpers.cpp.o

.PHONY : MPAGSCipher/CommandLineHelpers.o

# target to build an object file
MPAGSCipher/CommandLineHelpers.cpp.o:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/CommandLineHelpers.cpp.o
.PHONY : MPAGSCipher/CommandLineHelpers.cpp.o

MPAGSCipher/CommandLineHelpers.i: MPAGSCipher/CommandLineHelpers.cpp.i

.PHONY : MPAGSCipher/CommandLineHelpers.i

# target to preprocess a source file
MPAGSCipher/CommandLineHelpers.cpp.i:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/CommandLineHelpers.cpp.i
.PHONY : MPAGSCipher/CommandLineHelpers.cpp.i

MPAGSCipher/CommandLineHelpers.s: MPAGSCipher/CommandLineHelpers.cpp.s

.PHONY : MPAGSCipher/CommandLineHelpers.s

# target to generate assembly for a file
MPAGSCipher/CommandLineHelpers.cpp.s:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/CommandLineHelpers.cpp.s
.PHONY : MPAGSCipher/CommandLineHelpers.cpp.s

MPAGSCipher/ProcessCommandLine.o: MPAGSCipher/ProcessCommandLine.cpp.o

.PHONY : MPAGSCipher/ProcessCommandLine.o

# target to build an object file
MPAGSCipher/ProcessCommandLine.cpp.o:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/ProcessCommandLine.cpp.o
.PHONY : MPAGSCipher/ProcessCommandLine.cpp.o

MPAGSCipher/ProcessCommandLine.i: MPAGSCipher/ProcessCommandLine.cpp.i

.PHONY : MPAGSCipher/ProcessCommandLine.i

# target to preprocess a source file
MPAGSCipher/ProcessCommandLine.cpp.i:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/ProcessCommandLine.cpp.i
.PHONY : MPAGSCipher/ProcessCommandLine.cpp.i

MPAGSCipher/ProcessCommandLine.s: MPAGSCipher/ProcessCommandLine.cpp.s

.PHONY : MPAGSCipher/ProcessCommandLine.s

# target to generate assembly for a file
MPAGSCipher/ProcessCommandLine.cpp.s:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/ProcessCommandLine.cpp.s
.PHONY : MPAGSCipher/ProcessCommandLine.cpp.s

MPAGSCipher/TransformChar.o: MPAGSCipher/TransformChar.cpp.o

.PHONY : MPAGSCipher/TransformChar.o

# target to build an object file
MPAGSCipher/TransformChar.cpp.o:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/TransformChar.cpp.o
.PHONY : MPAGSCipher/TransformChar.cpp.o

MPAGSCipher/TransformChar.i: MPAGSCipher/TransformChar.cpp.i

.PHONY : MPAGSCipher/TransformChar.i

# target to preprocess a source file
MPAGSCipher/TransformChar.cpp.i:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/TransformChar.cpp.i
.PHONY : MPAGSCipher/TransformChar.cpp.i

MPAGSCipher/TransformChar.s: MPAGSCipher/TransformChar.cpp.s

.PHONY : MPAGSCipher/TransformChar.s

# target to generate assembly for a file
MPAGSCipher/TransformChar.cpp.s:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/MPAGSCipher/TransformChar.cpp.s
.PHONY : MPAGSCipher/TransformChar.cpp.s

mpags-cipher.o: mpags-cipher.cpp.o

.PHONY : mpags-cipher.o

# target to build an object file
mpags-cipher.cpp.o:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/mpags-cipher.cpp.o
.PHONY : mpags-cipher.cpp.o

mpags-cipher.i: mpags-cipher.cpp.i

.PHONY : mpags-cipher.i

# target to preprocess a source file
mpags-cipher.cpp.i:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/mpags-cipher.cpp.i
.PHONY : mpags-cipher.cpp.i

mpags-cipher.s: mpags-cipher.cpp.s

.PHONY : mpags-cipher.s

# target to generate assembly for a file
mpags-cipher.cpp.s:
	$(MAKE) -f CMakeFiles/mpags-cipher.dir/build.make CMakeFiles/mpags-cipher.dir/mpags-cipher.cpp.s
.PHONY : mpags-cipher.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package"
	@echo "... test"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... mpags-cipher"
	@echo "... MPAGSCipher"
	@echo "... testHello"
	@echo "... testCatch"
	@echo "... testTransformChar"
	@echo "... MPAGSCipher/CaesarCipher.o"
	@echo "... MPAGSCipher/CaesarCipher.i"
	@echo "... MPAGSCipher/CaesarCipher.s"
	@echo "... MPAGSCipher/CommandLineHelpers.o"
	@echo "... MPAGSCipher/CommandLineHelpers.i"
	@echo "... MPAGSCipher/CommandLineHelpers.s"
	@echo "... MPAGSCipher/ProcessCommandLine.o"
	@echo "... MPAGSCipher/ProcessCommandLine.i"
	@echo "... MPAGSCipher/ProcessCommandLine.s"
	@echo "... MPAGSCipher/TransformChar.o"
	@echo "... MPAGSCipher/TransformChar.i"
	@echo "... MPAGSCipher/TransformChar.s"
	@echo "... mpags-cipher.o"
	@echo "... mpags-cipher.i"
	@echo "... mpags-cipher.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

